name: Build and Publish Rust Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Install dependencies and build the project
      - name: Build project
        run: |
          cargo build --release

      # Publish the built binary as an artifact
      - name: Upload Rust binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: rust-binary
          path: target/release/your-binary-name
